[package]
name = "hew"
version = "0.4.3"
edition = "2026"

[dependencies]
gramide = { git = "https://github.com/O6lvl4/gramide", tag = "v0.1.3" }
gramide_almide = { git = "https://github.com/O6lvl4/gramide-almide", tag = "v0.1.2" }
gramide_go = { git = "https://github.com/O6lvl4/gramide-go", tag = "v0.1.2" }
gramide_rust = { git = "https://github.com/O6lvl4/gramide-rust", tag = "v0.1.2" }
gramide_python = { git = "https://github.com/O6lvl4/gramide-python", tag = "v0.1.0" }
gramide_javascript = { git = "https://github.com/O6lvl4/gramide-javascript", tag = "v0.2.2" }
gramide_typescript = { git = "https://github.com/O6lvl4/gramide-typescript", tag = "v0.2.1" }
