[package]
name = "hew"
version = "0.4.11"
edition = "2026"

[dependencies]
gramide = { git = "https://github.com/O6lvl4/gramide", tag = "v0.2.5" }
gramide_almide = { git = "https://github.com/O6lvl4/gramide-almide", tag = "v0.1.8" }
gramide_go = { git = "https://github.com/O6lvl4/gramide-go", tag = "v0.1.8" }
gramide_rust = { git = "https://github.com/O6lvl4/gramide-rust", tag = "v0.1.9" }
gramide_python = { git = "https://github.com/O6lvl4/gramide-python", tag = "v0.1.7" }
gramide_javascript = { git = "https://github.com/O6lvl4/gramide-javascript", tag = "v0.3.6" }
gramide_typescript = { git = "https://github.com/O6lvl4/gramide-typescript", tag = "v0.3.6" }
